// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbx

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Snippet struct {
	ID      int32
	Title   string
	Content string
	Created pgtype.Timestamptz
	Expires pgtype.Timestamptz
}
