// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snippets.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSnippet = `-- name: CreateSnippet :one
INSERT INTO snippets (title, content, created, expires)
VALUES ($1, $2, $3, $4)
RETURNING id, title, content, created, expires
`

type CreateSnippetParams struct {
	Title   string
	Content string
	Created pgtype.Timestamptz
	Expires pgtype.Timestamptz
}

func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) (Snippet, error) {
	row := q.db.QueryRow(ctx, createSnippet,
		arg.Title,
		arg.Content,
		arg.Created,
		arg.Expires,
	)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Created,
		&i.Expires,
	)
	return i, err
}

const deleteSnippet = `-- name: DeleteSnippet :exec
DELETE FROM snippets
WHERE id = $1
`

func (q *Queries) DeleteSnippet(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSnippet, id)
	return err
}

const getActiveSnippetsLimit10 = `-- name: GetActiveSnippetsLimit10 :many
SELECT id, title, content, created, expires FROM snippets
    WHERE expires > NOW() ORDER BY id DESC LIMIT 10
`

func (q *Queries) GetActiveSnippetsLimit10(ctx context.Context) ([]Snippet, error) {
	rows, err := q.db.Query(ctx, getActiveSnippetsLimit10)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Created,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnippetNotExpired = `-- name: GetSnippetNotExpired :one
SELECT id, title, content, created, expires FROM snippets
WHERE expires > NOW() AND id = $1
`

func (q *Queries) GetSnippetNotExpired(ctx context.Context, id int32) (Snippet, error) {
	row := q.db.QueryRow(ctx, getSnippetNotExpired, id)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Created,
		&i.Expires,
	)
	return i, err
}

const listSnippets = `-- name: ListSnippets :many
SELECT id, title, expires FROM snippets ORDER BY title
`

type ListSnippetsRow struct {
	ID      int32
	Title   string
	Expires pgtype.Timestamptz
}

func (q *Queries) ListSnippets(ctx context.Context) ([]ListSnippetsRow, error) {
	rows, err := q.db.Query(ctx, listSnippets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnippetsRow
	for rows.Next() {
		var i ListSnippetsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Expires); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
